version: '3.8'

services:
  # Laravel service (PHP + Apache)
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile # You should create a Dockerfile in the backend folder
    container_name: laravel_app
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - ./backend/.docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - app_network
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
      - DB_HOST=mysql
      - DB_DATABASE=laravel
      - DB_USERNAME=user
      - DB_PASSWORD=root
    working_dir: /var/www/html
    depends_on:
      - mysql
    command: apache2-foreground

  # Next.js service (Node.js)
  nextjs:
    build:
      context: ./frontend
      dockerfile: Dockerfile # You should create a Dockerfile in the frontend folder
    container_name: nextjs_app
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm run dev
    ports:
      - "3000:3000"
    networks:
      - app_network
    depends_on:
      - app

  # MySQL Database service
  mysql:
    image: mysql:8
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge